hmcts/pcs-frontend

charts/pcs-frontend/Chart.yaml
charts/pcs-frontend/values.yaml

Fix ingress url

---

src/main/modules/appinsights/index.ts

[HDPI-88](https://tools.hmcts.net/jira/browse/HDPI-88)
Changing cloud role declaration to allow for correct node naming.
None

HDPI-88 - Assigning cloud role before starting appInsights

---

charts/pcs-frontend/Chart.yaml
charts/pcs-frontend/values.yaml
config/custom-environment-variables.json
config/default.json
package.json
src/main/routes/health.ts
src/main/routes/info.ts
yarn.lock

https://tools.hmcts.net/jira/browse/HDPI-75

added healthcheck for api

---

src/main/routes/home.ts
src/main/views/home.njk

[HDPI-89](https://tools.hmcts.net/jira/browse/HDPI-89)
Remove the viewcount on PCS homepage
None

HDPI-89 - Remove view count on application homepage

---

src/test/unit/modules/appinsights/index.test.ts
src/test/unit/routes/info.test.ts
src/test/unit/sample.ts

Adding unit tests

---

Jenkinsfile_CNP
package.json
src/test/functional/basic.spec.ts
src/test/functional/helpers/accessibilityTestHelper.ts
yarn.lock

[HDPI-96](https://tools.hmcts.net/jira/browse/HDPI-96)
Adding axe core to the frontend application.
None, configuration

HDPI-96 - Adding accessibility test helper

---

package.json
src/test/functional/helpers/runChangedTestHelper.ts
yarn.lock

[HDPI-95](https://tools.hmcts.net/jira/browse/HDPI-95)
Adding changed test runner, so only .spec files with that are new or with changes are ran, speeding up local test development.
Manual implementation changes.

HDPI-95 - Adding run chnaged tests helper

---

Jenkinsfile_nightly
README.md
src/test/config.ts

[HDPI-100](https://tools.hmcts.net/jira/browse/HDPI-100)
Updating README.md for testing documentation
None, documentation update.

HDPI-100 - Updating README.md for testing

---

yarn.lock

Reverts hmcts/pcs-frontend#151

Revert "Update dependency sass to v1.83.0"

---

charts/pcs-frontend/Chart.yaml

Bump version

---

charts/pcs-frontend/Chart.yaml

Downgrade redis to 20.3

---

.gitignore
package.json
src/main/server.ts
yarn.lock

This will resolve https://github.com/hmcts/pcs-frontend/security/dependabot/1

Removing deprecated request package

---

charts/pcs-frontend/Chart.yaml

Try using oci url as suggested by platops

---

Jenkinsfile_CNP
package.json
yarn.lock

https://tools.hmcts.net/jira/browse/HDPI-276
This adds the dependency @types/git-rev-sync that was removed by mistake in another PR, this allows the project to be build locally with no errors.
PR is green, pact is published and code builds locally with no errors.

HDPI-276 fix

---

README.md

See [HDPI-599](https://tools.hmcts.net/jira/browse/PROJ-HDPI-599)
Minor updates to the readme to fix the URL for the healthcheck endpoint and to add details of the info endpoint.
n/a

HDPI-599: Minor updates to README

---

config/custom-environment-variables.json
config/default.json
jest.config.js
sonar-project.properties
src/main/modules/http/index.ts
src/main/modules/index.ts
src/main/modules/s2s/index.ts
src/main/modules/s2s/s2s.interface.ts
src/main/routes/dashboard.ts
src/main/server.ts
src/main/services/pcsApi/dashboardTaskGroup.interface.ts
src/main/services/pcsApi/pcsApiService.ts
src/main/views/components/taskGroup/applications/Task.AAA6.Applications.Contact.njk
src/test/unit/modules/http/http.test.ts
src/test/unit/modules/s2s/__mocks__/jose.ts
src/test/unit/modules/s2s/index.test.ts
src/test/unit/routes/dashboard.test.ts
src/test/unit/services/pcsApi/pcsApiService.test.ts
src/types/courtVenue.interface.ts
src/types/global.d.ts

https://tools.hmcts.net/jira/browse/HDPI-511

fix: s2s token not being picked up correctly, refactored

---

src/test/ui/functional/home.spec.ts

https://tools.hmcts.net/jira/browse/HDPI-877
Skipping the functional test temporarily until AAT gets fixed

Functional test temporarily disabled

---

Jenkinsfile_CNP
README.md
playwright.config.ts
src/test/ui/functional/home.spec.ts

https://tools.hmcts.net/jira/browse/HDPI-895
Resumed functional testing (As the issue DTSPO-26147 in staging is now resolved) and enabled html reports for the pipelines. 

Resumed functional testing in pcs-frontend

---

src/test/unit/modules/oidc/oidc.test.ts

N/A
Sonarcloud is failing with code coverage on master, this should fix that.
Running the new tests locally.

Upping OIDC code coverage

---

Jenkinsfile_CNP
src/test/ui/common/helpers/idam-helpers/idam.helper.ts
src/test/ui/common/helpers/login.helper.ts
src/test/ui/functional/dashboard.spec.ts
src/test/ui/functional/home.spec.ts

**Jira link**
[HDPI-1244](https://tools.hmcts.net/jira/browse/HDPI-1244)
1. Clean up across helpers and tests to remove process.env
2.  Attach URL to Reports 
1. Tested the changes locally, and attaching report from build.

House Keeping work: removing process.env to access variables

---

package.json
yarn-audit-known-issues
yarn.lock

https://tools.hmcts.net/jira/browse/HDPI-1363
removed stub definitions and updated packages for audit issues

chore: audit issues

---

charts/pcs-frontend/Chart.yaml
charts/pcs-frontend/values.yaml
config/default.json

HDPI-699: reverting ccd url
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
HDPI-699: reverting ccd url

HDPI-699: reverting ccd url

---

docker-compose.yml

Update bitnami acr path
After 28th august, bitnami are moving images to a ACR repository
See [HDPI-1601](https://tools.hmcts.net/jira/browse/HDPI-1601)

HDPI-1601: Update bitnami acr path
